global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'loki'
    static_configs:
      - targets: ['192.168.101.67:3100']
  - job_name: 'server'
    static_configs:
      - targets:
          - 192.168.101.67:9100